services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./api-gateway/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
     - app-network

  api-gateway-server:
    container_name: api-gateway-server
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file:  
      - ./api-gateway/.env
    volumes:
      - ./api-gateway/.env:/app/.env
    networks:
      - app-network

  auth-service-postgres:
    image: postgres:15
    env_file:
      - ./authorization/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./authorization/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app-network

  auth-service-redis:
    image: redis:7
    env_file:
      - ./authorization/.env
    command: redis-server --requirepass 123
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network

  auth-server:
    container_name: auth-server
    build:
      context: ./authorization
      dockerfile: Dockerfile
    env_file:
      - ./authorization/.env
    volumes:
      - ./authorization/.env:/app/.env
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:


networks:
  app-network:
    driver: bridge
