services:
  review-service-postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
  
  review-service-redis:
    image: redis:7
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data1:/data
    ports:
      - "6380:6379"
    restart: always
  
volumes:
  postgres_data1:
  redis_data1:

